### ISSUE TITLE
PIL.UnidentifiedImageError: cannot identify image file 'temp/test/!00001.pdg'

### ISSUE THREAD

**Issue by qiaoxiayu** [FinleyGe/pdg2pdf-linux#1]
Traceback (most recent call last):
  File "test.py", line 113, in <module>
    main()
  File "test.py", line 110, in main
    pdg2pdf(pdgfile, param[2])
  File "test.py", line 73, in pdg2pdf
    image_list.append(Image.open(file_path + t))
  File "/usr/local/lib/python3.8/dist-packages/PIL/Image.py", line 3298, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file 'temp/test/!00001.pdg'

**Comment by FinleyGe** [comment]
Maybe your pdg file does not have a TOC page, whose file name should like `!000001.pdg`.
But In my code I missed this.
So maybe you can modify the source code like this
at line 71

```py
if toc != []:
    for t in toc:
        # ...
```

Could you please patse the file tree of the pdg here,
and test the modified code?

**Comment by FinleyGe** [comment]
If this is helpful please open a pull request :)

**Comment by qiaoxiayu** [comment]
还是不行呀 我弄不懂python
Traceback (most recent call last):
  File "test.py", line 114, in <module>
    main()
  File "test.py", line 111, in main
    pdg2pdf(pdgfile, param[2])
  File "test.py", line 74, in pdg2pdf
    image_list.append(Image.open(file_path + t))
  File "/usr/local/lib/python3.8/dist-packages/PIL/Image.py", line 3298, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file 'temp/test/!00001.pdg'



错误一直出在这行: image_list.append(Image.open(file_path + t))

**Comment by qiaoxiayu** [comment]
是不是我环境啥的不行呢 PIL这个东西报错了

**Comment by FinleyGe** [comment]
我的意思是我代码里面有问题：如果你的这个pdg文件里面没有包含toc（目录），那么就会找不到文件
自然会报这个错，解决方法就是如我所说，修改71行附近的逻辑，在for之前判断一下列表是否为空，如果是空就不进循环，如果不为空就进循环。
因为你并没有贴出你的pdg文件的文件结构，所以我的建议是在你那边测试一下，如果我说的方法是可以的就ok。

我当时开发的时候用的应该至少是python3.10，这一点我没有提到确实是我的错误，但是这里应该没有环境问题。

**Comment by FinleyGe** [comment]
搞不定的话直接把你的pdg mail给我，我去看一下是什么情况。

202105130406@zjut.edu.cn

**Comment by FinleyGe** [comment]
So sorry that I can not solve this right now.
The PDG type is a kind of commercial file type that there are few documents that I can refer.
I find this blog:
https://www.cnblogs.com/stronghorse/p/4913239.html

The file you gave me is `03H` type, which is encrypted CCITT G4 type.
I have no idea with it.
So maybe you can use [strnghrs](https://www.cnblogs.com/stronghorse/)'s Pdg2pics (Windows only)
He maybe used Super Star Reader's `dll` file.

很抱歉我暂时想不到办法解决这个问题
PDG格式是一种商业格式，网络上基本找不到什么资料。
找到一篇文章，你发给我的这个格式是 03H，加密的 CCITT G4 格式
所以你或许可以直接用他的pdg2pics （只有windows）
他可能是直接用了超星阅读器的dll文件。

**Comment by FinleyGe** [comment]
PDG 格式太复杂了，而且是商业公司的格式，没有开源。
很早之前虽然有人逆向分析了这个格式，发布的工具也没有开源。
而且也应该没有逆向分析出超星具体的加密方式，所以我现在也没有什么好办法

你给我发的这个我看了一下，应该是如大神所说的经过加密的图像文件。
对于你这个问题的解决办法我想是只有去使用那位大神“老马”的软件（网上找的到，只有windows）
如果有时间的话我会去研究一下，
不过需要学习逆向分析等等的知识，所以要解决这个问题可能要等很久咯
